"""Adicionar tabela Anotacao e colunas faltantes

Revision ID: 30ce17c5a7ef
Revises: 
Create Date: 2025-06-21 15:42:39.783547

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '30ce17c5a7ef'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('anotacoes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('titulo', sa.String(length=200), nullable=True),
    sa.Column('conteudo', sa.Text(), nullable=False),
    sa.Column('data_criacao', sa.DateTime(), nullable=True),
    sa.Column('data_atualizacao', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('capital_giro',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('valor', sa.Float(), nullable=True),
    sa.Column('atualizado_em', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('contas_pagar',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('descricao', sa.String(length=200), nullable=False),
    sa.Column('valor', sa.Float(), nullable=False),
    sa.Column('data_vencimento', sa.Date(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('tipo', sa.String(length=50), nullable=True),
    sa.Column('data_pagamento', sa.DateTime(), nullable=True),
    sa.Column('criada_em', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('estoque_insumos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('socia', sa.String(length=50), nullable=False),
    sa.Column('nome_insumo', sa.String(length=100), nullable=False),
    sa.Column('quantidade', sa.Float(), nullable=True),
    sa.Column('unidade', sa.String(length=20), nullable=False),
    sa.Column('atualizado_em', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('socia', 'nome_insumo', name='uq_socia_insumo')
    )
    op.create_table('lucros_pendentes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('socia', sa.String(length=50), nullable=False),
    sa.Column('descricao', sa.String(length=200), nullable=False),
    sa.Column('valor', sa.Float(), nullable=False),
    sa.Column('data_adicao', sa.DateTime(), nullable=True),
    sa.Column('origem', sa.String(length=100), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('precos_venda',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('canal', sa.String(length=50), nullable=False),
    sa.Column('tipo_pacote', sa.String(length=50), nullable=False),
    sa.Column('quantidade_balas', sa.Integer(), nullable=False),
    sa.Column('preco', sa.Float(), nullable=False),
    sa.Column('ativo', sa.Boolean(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('canal', 'tipo_pacote', name='uq_canal_pacote')
    )
    op.create_table('receitas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.Column('descricao', sa.Text(), nullable=True),
    sa.Column('balas_por_receita', sa.Integer(), nullable=True),
    sa.Column('custo_por_bala', sa.Float(), nullable=True),
    sa.Column('ativa', sa.Boolean(), nullable=True),
    sa.Column('is_default', sa.Boolean(), nullable=True),
    sa.Column('criada_em', sa.DateTime(), nullable=True),
    sa.Column('atualizada_em', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nome')
    )
    op.create_table('transacoes_financeiras',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tipo', sa.String(length=50), nullable=False),
    sa.Column('descricao', sa.String(length=200), nullable=False),
    sa.Column('valor', sa.Float(), nullable=False),
    sa.Column('data_transacao', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('estoque_balas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('detentor', sa.String(length=50), nullable=False),
    sa.Column('receita_id', sa.Integer(), nullable=False),
    sa.Column('quantidade', sa.Integer(), nullable=True),
    sa.Column('atualizado_em', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['receita_id'], ['receitas.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('detentor', 'receita_id', name='uq_detentor_receita')
    )
    op.create_table('ingredientes_receita',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('receita_id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.Column('quantidade', sa.Float(), nullable=False),
    sa.Column('unidade', sa.String(length=20), nullable=False),
    sa.ForeignKeyConstraint(['receita_id'], ['receitas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('producoes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('socia_produtora', sa.String(length=50), nullable=False),
    sa.Column('receita_id', sa.Integer(), nullable=False),
    sa.Column('receitas_produzidas', sa.Integer(), nullable=False),
    sa.Column('balas_produzidas', sa.Integer(), nullable=False),
    sa.Column('data_producao', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['receita_id'], ['receitas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('vendas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('socia_produtora', sa.String(length=50), nullable=False),
    sa.Column('estoque_saida', sa.String(length=50), nullable=False),
    sa.Column('receita_id', sa.Integer(), nullable=False),
    sa.Column('canal_venda', sa.String(length=50), nullable=False),
    sa.Column('tipo_pacote', sa.String(length=50), nullable=True),
    sa.Column('quantidade_balas', sa.Integer(), nullable=False),
    sa.Column('valor_bruto', sa.Float(), nullable=False),
    sa.Column('custo', sa.Float(), nullable=False),
    sa.Column('lucro_liquido', sa.Float(), nullable=False),
    sa.Column('data_venda', sa.DateTime(), nullable=True),
    sa.Column('fonte_ifood', sa.String(length=50), nullable=True),
    sa.Column('id_recebivel', sa.String(length=50), nullable=True),
    sa.Column('data_prevista', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['receita_id'], ['receitas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('contas_receber',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('venda_id', sa.Integer(), nullable=True),
    sa.Column('descricao', sa.String(length=200), nullable=False),
    sa.Column('valor', sa.Float(), nullable=False),
    sa.Column('data_vencimento', sa.Date(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('fonte', sa.String(length=50), nullable=True),
    sa.Column('criada_em', sa.DateTime(), nullable=True),
    sa.Column('data_recebimento', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['venda_id'], ['vendas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('contas_receber')
    op.drop_table('vendas')
    op.drop_table('producoes')
    op.drop_table('ingredientes_receita')
    op.drop_table('estoque_balas')
    op.drop_table('transacoes_financeiras')
    op.drop_table('receitas')
    op.drop_table('precos_venda')
    op.drop_table('lucros_pendentes')
    op.drop_table('estoque_insumos')
    op.drop_table('contas_pagar')
    op.drop_table('capital_giro')
    op.drop_table('anotacoes')
    # ### end Alembic commands ###
